### ISSUE TITLE
Cannot build chapter 5 image

### ISSUE THREAD

**Issue by hernihub** [ihuaylupo/manning-smia#15]
Hi. I just bought the book and tried to do as chapter 5 readme indicates:  **mvn clean package dockerfile:build** but got this:

`Could not build image: Caused by: com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: com.spotify.docker.client.shaded.org.apache.http.conn.HttpHostConnectException: Connect to 192.168.99.100:2376 [/192.168.99.100] failed: Connection timed out: connect`

I don't know where or why is trying to connect to 192.168.99.100. Can't go past this part, I'm stuck and probably the fix is easy.

Any help would be really appreciated.

**UPDATE**
As a matter of fact, I cannot build any chapter, same error. Also, when I run the command, the INFO part says **dockerfile: null** and **Path(dockerfile): null**

**Comment by balabasciucpe** [comment]
Hei, for Config Server running on Docker, we need somehow to make the other 2 services to wait for Config Server to accept connections, depends_on only waits to start, so even config server is starting, after that the Licensing-Service start next second -> time out -> can't obtain any proper configuration because Config Server didn't start completly... i'm stuck at that part too now, look some help: `https://stackoverflow.com/questions/57739617/spring-config-server-not-reachable-with-docker-compose-until-client-is-restarted`    `https://www.youtube.com/watch?v=e3YERpG2rMs&list=PLVz2XdJiJQxzMiFDnwxUDxmuZQU3igcBb&index=2`

Edit: if i'm gonna somehow doing, i'm going to live the "solution" here
Edit2: 192.168.99.100 it's your docker machine ip, but you need to provide some port to connect to that ip (for example -> http://192.168.99.100:9090/ 9090 beeing the port, and your machine ip being instead of showing localhost), look at that yt video

**Comment by hernihub** [comment]
Make sure you have all previous data from Docket Toolbox and Oracle Virtual box deleted, including env variables. After doing that and upgrading to Windows Pro, unfortunately, it works.
Refer to this: https://github.com/docker/for-win/issues/1746#issuecomment-384940428
I don't if WSL 2 would have worked without upgrading Windows, I fear. So give it a try if you have Windows 10 Home or any other build that needs WSL 2 to make Docker work.
