### ISSUE TITLE
Chapter 5 docker-compose -f docker/docker-compose.yml up Fails.

### ISSUE THREAD

**Issue by ezazpi** [ihuaylupo/manning-smia#5]
I cloned the projects and followed the instructions in the md, but docker-compose is failing.  My understanding is docker/docker-compose.yml must be processed first to start Postgres and configserver.  After that, the licensing-service can be started.  The attached file shows the output from processing docker/docker-compose.yml.

[chapter5 docker-compose -f docker docker-compose.yml up.txt](https://github.com/ihuaylupo/manning-smia/files/5180987/chapter5.docker-compose.-f.docker.docker-compose.yml.up.txt)

**Comment by ihuaylupo** [comment]
Can you run the docker-compose up command again? It should be fixed now. The problem was that I was using an incorrect database service id on the licensing-service-dev.properties file in the configuration GitHub repository.

The part that you previously mentioned is right, but for that specific case, I added the `depends on` section in the docker-compose file for the licensing-service. The requirement to start the licensing service is to have a database instance healthy and a config server instance up and running.

**Comment by ezazpi** [comment]
I reran `C:\Users\ezazpi\Documents\IntelliJ\manning-smia\chapter5>docker-compose -f docker\docker-compose.yml up` and the postgres, licensingservice, and configserver successfully started.  However, when I ran a database query, postgres couldn't find the license table.  I'll open a separate issue.  Thank you. 

`C:\Users\ezazpi\Documents\IntelliJ\manning-smia\chapter5>docker ps`
CONTAINER ID        IMAGE                                     COMMAND                  CREATED              STATUS                        PORTS                    NAMES
af298ee5f75f        ostock/licensing-service:0.0.2-SNAPSHOT   "java -cp app:app/li…"   About a minute ago   Up About a minute             0.0.0.0:8080->8080/tcp   docker_licensingservice_1
0475d6887237        ostock/configserver:0.0.1-SNAPSHOT        "java -cp app:app/li…"   About a minute ago   Up About a minute             0.0.0.0:8071->8071/tcp   docker_configserver_1
2352673e6083        postgres:latest                           "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:5432->5432/tcp   docker_database_1
